apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb_iot
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: iot-lab
      defaultBucket: iot_data
      tlsSkipVerify: true
    secureJsonData:
      token: iot-token-123
